version: '3' 

services: 

  ex_3_4_frontend:  
    image: frontend:final
    build: ./frontend/
    ports: 
      - 5000:5000
    container_name: ex_3_4_frontend
    environment:
      - API_URL=api

  ex_3_4_backend:  
    image: backend:final
    build: ./backend/
    volumes: 
      - ./logs.txt:/usr/local/www/backend/logs.txt
    ports: 
      - 8000:8000
    environment:
      - REDIS=ex_3_4_redis
      - REDIS_PORT=6379
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_HOST=ex_3_4_postgres
      - FRONT_URL=localhost
    container_name: ex_3_4_backend
    restart: unless-stopped

  ex_3_4_redis:
    image: redis
    ports: 
      - 6379:6379
    container_name: ex_3_4_redis
  
  ex_3_4_postgres:
    image: postgres
    restart: unless-stopped
    container_name: ex_3_4_postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    volumes:
      - database:/var/lib/postgresql/data

  ex_3_4_nginx:
    container_name: ex_3_4_nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - ex_3_4_frontend
      - ex_3_4_backend

volumes:
  database: